Cubic ERP/Areas/Finance/Models/BankAccount.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Cubic_ERP.Areas.Finance.Models
{
    public class BankAccount
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        public int AccountId { get; set; }
        public Account Account { get; set; }

        public int? MaintainedByUserId { get; set; }
        public bool IsMerchantAccount { get; set; }
        public int? OfficeId { get; set; }

        [StringLength(128)]
        public string BankName { get; set; }

        [StringLength(128)]
        public string BankBranch { get; set; }

        [StringLength(128)]
        public string BankContactNumber { get; set; }

        [StringLength(128)]
        public string BankAccountNumber { get; set; }

        [StringLength(128)]
        public string BankAccountType { get; set; }

        [StringLength(50)]
        public string Street { get; set; }

        [StringLength(50)]
        public string City { get; set; }

        [StringLength(50)]
        public string State { get; set; }

        [StringLength(50)]
        public string Country { get; set; }

        [StringLength(50)]
        public string Phone { get; set; }

        [StringLength(50)]
        public string Fax { get; set; }

        [StringLength(50)]
        public string Cell { get; set; }

        [StringLength(128)]
        public string RelationshipOfficerName { get; set; }
        [StringLength(128)]
        public string RelationshipOfficerContactNumber { get; set; }


        public int? AuditUserId { get; set; }
        public DateTimeOffset? AuditTimeStamp { get; set; }
        public bool? Deleted { get; set; }
    }
}

Cubic ERP/Areas/Finance/Controllers/API/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Cubic_ERP.Models;

namespace Cubic_ERP.Areas.Finance.Controllers.API
{
    public class BankAccountsController : ApiController
    {
        private ApplicationDbContext _context;

        public BankAccountsController()
        {
            _context=new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // Get list of bank accounts.
        [Route("finance/api/bankaccounts")]
        public IHttpActionResult GetBankAccounts()
        {

            return Ok(_context.BankAccounts.ToList());
        }

        //Delete bank accoount with this id
        [HttpDelete]
        [Route("finance/api/bankaccounts/{id}")]
        public IHttpActionResult DeleteBankAccount(int id)
        {
            var bankAccount = _context.BankAccounts.Find(id);
            if (bankAccount==null)
            {
                return NotFound();
            }

            _context.BankAccounts.Remove(bankAccount);
            _context.SaveChanges();
            return Ok();
        }
    }
}

Cubic ERP/Areas/Finance/Controllers/Setups/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Cubic_ERP.Areas.Finance.Dtos;
using Cubic_ERP.Areas.Finance.Models;
using Cubic_ERP.Areas.Finance.ViewModels;
using Cubic_ERP.Models;

namespace Cubic_ERP.Areas.Finance.Controllers.Setups
{
    public class BankAccountsController : Controller
    {
        private ApplicationDbContext _context;

        public BankAccountsController()
        {
            _context=new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Finance/BankAccounts
        public ActionResult Index()
        {
            var bankAccounts = _context.BankAccounts.ToList();
            return View(bankAccounts);
        }

        public ActionResult New()
        {
            var bankAccountDto = new BankAccountDto
            {
                Id = 0
            };
            var baViewModel = new BankAccountFormViewModel
            {
                ActionIndicator = 1,
                BankAccountDto = bankAccountDto,
                AccountDtos = _context.Accounts.ToList().Select(Mapper.Map<Account, AccountDto>)
            };
            return View("BankAccountForm", baViewModel);
        }

        public ActionResult Edit(int id)
        {
            var bankAccountInDb = _context.BankAccounts.Find(id);
            var bankAccountDto = Mapper.Map<BankAccount, BankAccountDto>(bankAccountInDb);
            var bafViewModel = new BankAccountFormViewModel
            {
                ActionIndicator = 2,
                BankAccountDto = bankAccountDto,
                AccountDtos = _context.Accounts.ToList().Select(Mapper.Map<Account, AccountDto>)
            };
            return View("BankAccountForm",bafViewModel);
        }

        [HttpPost]
        public ActionResult Save(BankAccountFormViewModel bafViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("BankAccountForm", bafViewModel);
            }
            //else everything is fine so we map and save
            if (bafViewModel.BankAccountDto.Id==0)//Then it's a new bank account
            {
                var bankaccount = Mapper.Map<BankAccountDto, BankAccount>(bafViewModel.BankAccountDto);
                _context.BankAccounts.Add(bankaccount);
                _context.SaveChanges();
            }else{
                var bankaccountInDb = _context.BankAccounts.Find(bafViewModel.BankAccountDto.Id);
                if (bankaccountInDb==null)
                {
                    return HttpNotFound();
                }
                Mapper.Map(bafViewModel.BankAccountDto, bankaccountInDb);
                _context.SaveChanges();
            }
           
            return RedirectToAction("Index");
        }
    }
}

Cubic ERP/Areas/Finance/Views/BankAccounts/BankAccountForm.cshtml
@model Cubic_ERP.Areas.Finance.ViewModels.BankAccountFormViewModel
@{
    ViewBag.Title = "BankAccountForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h3 class="pull-left">Bank Accounts</h3>
    <a id="form-navigator" href="@Url.Action("Index", "BankAccounts")" class="btn btn-success btn-sm pull-right"><i class="glyphicon glyphicon-arrow-left"></i></a>
    <hr id="hr-separator" />
</div>

<div>
    <div class="col-md-5">
        @using (Html.BeginForm("Save", "BankAccounts", FormMethod.Post,new{@id="form-submit"}))
        {

            <div class="form-group">
                @Html.LabelFor(m => m.BankAccountDto.BankName)
                @Html.TextBoxFor(m => m.BankAccountDto.BankName, new { @class = "form-control", @id="first-form-input" })
                @Html.ValidationMessageFor(m => m.BankAccountDto.BankName)
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.BankAccountDto.BankBranch)
                    @Html.TextBoxFor(m => m.BankAccountDto.BankBranch, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.BankAccountDto.BankBranch)
                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.BankAccountDto.OfficeId)
                    @Html.TextBoxFor(m => m.BankAccountDto.OfficeId, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.BankAccountDto.OfficeId)
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.BankAccountDto.Name)
                    @Html.TextBoxFor(m => m.BankAccountDto.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.BankAccountDto.Name)
                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.BankAccountDto.AccountId)
                    @Html.DropDownListFor(m => m.BankAccountDto.AccountId, new SelectList(Model.AccountDtos, "Id", "AccountName"), "Select Account", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.BankAccountDto.AccountId)
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.BankAccountDto.BankAccountNumber)
                    @Html.TextBoxFor(m => m.BankAccountDto.BankAccountNumber, new
                    {
                        @class = "form-control"})
                    @Html.ValidationMessageFor(m => m.BankAccountDto.BankAccountNumber)
                </div>
            </div>
            <div class="checkbox">
                <label>
                    @Html.CheckBoxFor(m => m.BankAccountDto.IsMerchantAccount) Is Merchant Account?
                </label>
            </div>
            @Html.HiddenFor(m => m.BankAccountDto.Id)

            if(Model.ActionIndicator == 1)
             {
                 <button class="btn btn-primary" type="submit">Save</button>
             }
             else
             {
                 <a href="#" class="btn btn-primary" id="js-edit">Save</a>
             }
            <a href="@Url.Action("Index","BankAccounts")" class="btn btn-default">Cancel</a>
        }
    </div>
</div>


@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(
            function() {
                $("#js-edit").on('click',
                    function () {

                        bootbox.confirm("Are you sure you want to Edit this item?",
                            function(result) {
                                if (result) {
                                    $("#form-submit").submit();
                                }
                            }
                        );
                    }
                );
                
            }
        );

    </script>
}

Cubic ERP/Areas/Finance/Views/BankAccounts/Index.cshtml
@model List<Cubic_ERP.Areas.Finance.Models.BankAccount>
@{
    ViewBag.Title = "Bank Accounts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@ViewBag.Title</h3>

<div>
    <a class="btn btn-default" href="@Url.Action("New","BankAccounts")">Add New</a>
</div>

<br/>
<table id="table-crud" class="table table-responsive table-striped">
    <thead>
    <tr>
        <th>Actions</th>
        <th>#</th>
        <th>Bank Name</th>
        <th>Bank Branch</th>
        <th>Office Name</th>
        <th>Account Name</th>
        <th>Account Number</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var bankaccount in Model)
    {
        <tr>
            <td>
                <a href="@Url.Action("Edit","BankAccounts", new {id=bankaccount.Id})"><span class="glyphicon glyphicon-edit"></span></a>
                <a href="#"><span class="glyphicon glyphicon-remove js-delete" data-bankaccount-id="@bankaccount.Id"></span></a>
            </td>
            <td>@bankaccount.Id</td>
            <td>@bankaccount.BankName</td>
            <td>@bankaccount.BankBranch</td>
            <td>@bankaccount.OfficeId</td>
            <td>@bankaccount.Name</td>
            <td>@bankaccount.BankAccountNumber</td>
        </tr>  
    }
    
    </tbody>
</table>
@section scripts
{
    @Scripts.Render("~/bundles/tableexport")

    <script type="text/javascript">
        $(document).ready(
            function () {
                var table = $("#table-crud").DataTable();

                $("#table-crud").on("click", ".js-delete",
                    function () {
                        var deleteLink = $(this);
                        bootbox.confirm("Are you sure you want to delete this item?",
                            function(result) {
                                if (result) {
                                    $.ajax({
                                        url: "/finance/api/bankaccounts/" + deleteLink.attr("data-bankaccount-id"),
                                        method: "DELETE",
                                        success: function() {
                                            console.log("Successfully deleted bank account: " + deleteLink.attr("data-bankaccount-id"));
                                            table.row(deleteLink.parents("tr")).remove().draw();
                                        }
                                    });
                                }
                            }
                        );
                    }
                );

                $("#table-crud").tableExport({
                        formats: ["xlsx","xls", "csv", "txt"],
                        fileName: "Bank Accounts",
                        position: "bottom"
                });

                
            }
        );
    </script>
}