Cubic ERP/Areas/Finance/Models/PaymentCard.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Cubic_ERP.Areas.Finance.Models
{
    public class PaymentCard
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Code { get; set; }

        [Required]
        [StringLength(128)]
        public string Name { get; set; }

        public int CardTypeId { get; set; }
        public CardType CardType { get; set; }

        public int? AuditUserId { get; set; }
        public DateTimeOffset? AuditTimeStamp { get; set; }
    }
}

Cubic ERP/Areas/Finance/Controllers/API/PaymentCardsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Cubic_ERP.Models;

namespace Cubic_ERP.Areas.Finance.Controllers.API
{
    public class PaymentCardsController : ApiController
    {
        private ApplicationDbContext _context;

        public PaymentCardsController()
        {
            _context=new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        //get list of payment cards
        [HttpGet]
        [Route("finance/api/paymentcards")]
        public IHttpActionResult GetPaymentCards()
        {
            return Ok(_context.PaymentCards.Include(p=>p.CardType).ToList());
        }

        //delete a payment card
        [HttpDelete]
        [Route("finance/api/paymentcards/{id}")]
        public IHttpActionResult DeletePaymentCard(int id)
        {
            var paymentCardInDb = _context.PaymentCards.Find(id);
            if (paymentCardInDb==null)
            {
                return NotFound();
            }
            _context.PaymentCards.Remove(paymentCardInDb);
            _context.SaveChanges();

            return Ok();
        }
    }
}

Cubic ERP/Areas/Finance/Controllers/Setups/PaymentCardsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cubic_ERP.Areas.Finance.Models;
using Cubic_ERP.Areas.Finance.ViewModels;
using Cubic_ERP.Models;

namespace Cubic_ERP.Areas.Finance.Controllers.Setups
{
    public class PaymentCardsController : Controller
    {
        private ApplicationDbContext _context;

        public PaymentCardsController()
        {
            _context=new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        
        // GET: Finance/PaymentCards
        public ActionResult Index()
        {
            var paymentCardsList = _context.PaymentCards.Include(p=>p.CardType).ToList();
            return View(paymentCardsList);
        }

        //create new payment card
        public ActionResult New()
        {
            var paymentCard = new PaymentCard
            {
                Id = 0
            };

            var paymentCardViewModel = new PaymentCardFormViewModel
            {
                ActionIndicator = 1,
                PaymentCard = paymentCard,
                CardTypes = _context.CardTypes.ToList()
            };
            return View("PaymentCardForm", paymentCardViewModel);
        }

        public ActionResult Edit(int id)
        {
            var paymentCardInDb = _context.PaymentCards.Find(id);
            if (paymentCardInDb==null)
            {
                return HttpNotFound();
            }
            var paymentCardViewModel = new PaymentCardFormViewModel
            {
                ActionIndicator = 2,
                PaymentCard = paymentCardInDb,
                CardTypes = _context.CardTypes.ToList()
            };
            return View("PaymentCardForm", paymentCardViewModel);
        }

        [HttpPost]
        public ActionResult Save(PaymentCardFormViewModel paymentCardViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("PaymentCardForm", paymentCardViewModel);
            }
            //check if it's a new payment card
            if (paymentCardViewModel.PaymentCard.Id==0)
            {
                var paymentCard = paymentCardViewModel.PaymentCard;
                _context.PaymentCards.Add(paymentCard);
                _context.SaveChanges();
            }
            else
            {
                var paymentCardInDb = _context.PaymentCards.Find(paymentCardViewModel.PaymentCard.Id);
                if (paymentCardInDb==null)
                {
                    return HttpNotFound();
                }
                paymentCardInDb.Code = paymentCardViewModel.PaymentCard.Code;
                paymentCardInDb.Name = paymentCardViewModel.PaymentCard.Name;
                paymentCardInDb.CardTypeId = paymentCardViewModel.PaymentCard.CardTypeId;

                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Cubic ERP/Areas/Finance/Views/PaymentCards/Index.cshtml
@model List<Cubic_ERP.Areas.Finance.Models.PaymentCard>
@{
    ViewBag.Title = "Payment Cards";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@ViewBag.Title</h3>

<div>
    <a class="btn btn-default" href="@Url.Action("New","PaymentCards")">Add New</a>
</div>

<br/>
<table id="table-crud" class="table table-responsive table-striped">
    <thead>
    <tr>
        <th>Actions</th>
        <th>#</th>
        <th>Payment Card Code</th>
        <th>Payment Card Name</th>
        <th>Card Type</th>
        
    </tr>
    </thead>
    <tbody>
    @foreach (var paymentCard in Model)
    {
        <tr>
            <td>
                <a href="@Url.Action("Edit","PaymentCards", new {id=paymentCard.Id})"><span class="glyphicon glyphicon-edit"></span></a>
                <a href="#"><span class="glyphicon glyphicon-remove js-delete" data-paymentcard-id="@paymentCard.Id"></span></a>
            </td>
            <td>@paymentCard.Id</td>
            <td>@paymentCard.Code</td>
            <td>@paymentCard.Name</td>
            <td>@paymentCard.CardType.Name</td>
            
        </tr>  
    }
    
    </tbody>
</table>
@section scripts
{
    @Scripts.Render("~/bundles/tableexport")

    <script type="text/javascript">
        $(document).ready(
            function () {
                var table = $("#table-crud").DataTable();

                $("#table-crud").on("click", ".js-delete",
                    function () {
                        var deleteLink = $(this);
                        bootbox.confirm("Are you sure you want to delete this item?",
                            function(result) {
                                if (result) {
                                    $.ajax({
                                        url: "/finance/api/paymentcards/" + deleteLink.attr("data-paymentcard-id"),
                                        method: "DELETE",
                                        success: function() {
                                            console.log("Successfully deleted Payment Card: " + deleteLink.attr("data-paymentcard-id"));
                                            table.row(deleteLink.parents("tr")).remove().draw();
                                        }
                                    });
                                }
                            }
                        );
                    }
                );

                $("#table-crud").tableExport({
                    formats: ["xlsx","xls", "csv", "txt"],
                    fileName: "Payment Cards",
                    position: "bottom"
                });

                
            }
        );
    </script>
}

Cubic ERP/Areas/Finance/Views/PaymentCards/PaymentCardForm.cshtml
@model Cubic_ERP.Areas.Finance.ViewModels.PaymentCardFormViewModel
@{
    ViewBag.Title = "Payment Cards";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h3 class="pull-left">@ViewBag.Title</h3>
    <a id="form-navigator" href="@Url.Action("Index", "PaymentCards")" class="btn btn-success btn-sm pull-right"><i class="glyphicon glyphicon-arrow-left"></i></a>
    <hr id="hr-separator" />
</div>

<div>
    <div class="col-md-5">
        @using (Html.BeginForm("Save", "PaymentCards", FormMethod.Post,new{@id="form-submit"}))
        {

            <div class="form-group">
                @Html.LabelFor(m => m.PaymentCard.Name)
                @Html.TextBoxFor(m => m.PaymentCard.Name, new { @class = "form-control", @id="first-form-input" })
                @Html.ValidationMessageFor(m => m.PaymentCard.Name)
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.PaymentCard.Code)
                    @Html.TextBoxFor(m => m.PaymentCard.Code, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.PaymentCard.Code)
                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.PaymentCard.CardTypeId)
                    @Html.DropDownListFor(m => m.PaymentCard.CardTypeId, new SelectList(Model.CardTypes, "Id", "Name"), "Select Card Type", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.PaymentCard.CardTypeId)
                </div>
            </div>
            
            
            @Html.HiddenFor(m => m.PaymentCard.Id)

            if(Model.ActionIndicator == 1)
            {
                <button class="btn btn-primary" type="submit">Save</button>
            }
            else
            {
                <a href="#" class="btn btn-primary" id="js-edit">Save</a>
            }
            <a href="@Url.Action("Index","PaymentCards")" class="btn btn-default">Cancel</a>
        }
    </div>
</div>


@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(
            function() {
                $("#js-edit").on('click',
                    function () {

                        bootbox.confirm("Are you sure you want to Edit this item?",
                            function(result) {
                                if (result) {
                                    $("#form-submit").submit();
                                }
                            }
                        );
                    }
                );
                
            }
        );

    </script>
}