Cubic ERP/Areas/Finance/Controllers/API/CardTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Cubic_ERP.Models;

namespace Cubic_ERP.Areas.Finance.Controllers.API
{
    public class CardTypesController : ApiController
    {
        private ApplicationDbContext _context;

        public CardTypesController()
        {
            _context=new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        //get list of card types
        [HttpGet]
        [Route("finance/api/cardtypes")]
        public IHttpActionResult GetCardTypesList()
        {
            return Ok(_context.CardTypes.ToList());
        }


        //delete a card type
        [HttpDelete]
        [Route("finance/api/cardtypes/{id}")]
        public IHttpActionResult DeleteCardType(int id)
        {
            var cardTypeInDb = _context.CardTypes.Find(id);
            if (cardTypeInDb==null)
            {
                return NotFound();
            }
            _context.CardTypes.Remove(cardTypeInDb);
            _context.SaveChanges();

            return Ok();
        }
    }
}

Cubic ERP/Areas/Finance/Controllers/Setups/CardTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cubic_ERP.Areas.Finance.Models;
using Cubic_ERP.Areas.Finance.ViewModels;
using Cubic_ERP.Models;

namespace Cubic_ERP.Areas.Finance.Controllers.Setups
{
    public class CardTypesController : Controller
    {
        private ApplicationDbContext _context;

        public CardTypesController()
        {
            _context=new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
           _context.Dispose();
        }


        // GET: Finance/CardTypes
        public ActionResult Index()
        {
            var cardtypeslist = _context.CardTypes.ToList();
            return View(cardtypeslist);
        }

        public ActionResult New()
        {
            var cardType = new CardType
            {
                Id = 0
            };

            var cardTypeViewModel = new CardTypeFormViewModel
            {
                ActionIndicator = 1,
                CardType = cardType
            };
            return View("CardTypeForm", cardTypeViewModel);
        }

        public ActionResult Edit(int id)
        {
            var cardTypeInDb = _context.CardTypes.Find(id);
            if (cardTypeInDb==null)
            {
                return HttpNotFound();
            }

            var cardtypeViewModel = new CardTypeFormViewModel
            {
                ActionIndicator = 2,
                CardType = cardTypeInDb
            };

            return View("CardTypeForm", cardtypeViewModel);
        }

        [HttpPost]
        public ActionResult Save(CardTypeFormViewModel cardTypeViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("CardTypeForm", cardTypeViewModel);
            }
            //else check if it's a new card type
            if (cardTypeViewModel.CardType.Id==0)
            {
                var cardType = cardTypeViewModel.CardType;
                _context.CardTypes.Add(cardType);
                _context.SaveChanges();
            }
            else
            {
                var cardTypeInDb = _context.CardTypes.Find(cardTypeViewModel.CardType.Id);
                if (cardTypeInDb==null)
                {
                    return HttpNotFound();
                }
                cardTypeInDb.Code = cardTypeViewModel.CardType.Code;
                cardTypeInDb.Name = cardTypeViewModel.CardType.Name;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Cubic ERP/Areas/Finance/Views/CardTypes/CardTypeForm.cshtml
@model Cubic_ERP.Areas.Finance.ViewModels.CardTypeFormViewModel
@{
    ViewBag.Title = "Card Types";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h3 class="pull-left">@ViewBag.Title</h3>
    <a id="form-navigator" href="@Url.Action("Index", "CardTypes")" class="btn btn-success btn-sm pull-right"><i class="glyphicon glyphicon-arrow-left"></i></a>
    <hr id="hr-separator" />
</div>

<div>
    <div class="col-md-5">
        @using (Html.BeginForm("Save", "CardTypes", FormMethod.Post, new { @id = "form-submit" }))
        {

            <div class="row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.CardType.Code)
                    @Html.TextBoxFor(m => m.CardType.Code, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.CardType.Code)
                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.CardType.Name)
                    @Html.TextBoxFor(m => m.CardType.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.CardType.Name)
                </div>
            </div>


            @Html.HiddenFor(m => m.CardType.Id)

            if (Model.ActionIndicator == 1)
            {
                <button class="btn btn-primary" type="submit">Save</button>
            }
            else
            {
                <a href="#" class="btn btn-primary" id="js-edit">Save</a>
            }
            <a href="@Url.Action("Index","CardTypes")" class="btn btn-default">Cancel</a>
        }
    </div>
</div>


@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(
            function() {
                $("#js-edit").on('click',
                    function () {

                        bootbox.confirm("Are you sure you want to Edit this item?",
                            function(result) {
                                if (result) {
                                    $("#form-submit").submit();
                                }
                            }
                        );
                    }
                );

            }
        );

    </script>
}

Cubic ERP/Areas/Finance/Views/CardTypes/Index.cshtml
@model IEnumerable<Cubic_ERP.Areas.Finance.Models.CardType>
@{
    ViewBag.Title = "Card Types";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@ViewBag.Title</h3>

<div>
    <a class="btn btn-default" href="@Url.Action("New","CardTypes")">Add New</a>
</div>

<br />
<table id="table-crud" class="table table-responsive table-striped">
    <thead>
        <tr>
            <th>Actions</th>
            <th>#</th>
            <th>Card Type Code</th>
            <th>Card Type Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cardType in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Edit","CardTypes", new {id=cardType.Id})"><span class="glyphicon glyphicon-edit"></span></a>
                    <a href="#"><span class="glyphicon glyphicon-remove js-delete" data-cardtype-id="@cardType.Id"></span></a>
                </td>
                <td>@cardType.Id</td>
                <td>@cardType.Code</td>
                <td>@cardType.Name</td>

            </tr>
        }

    </tbody>
</table>
@section scripts
{
    @Scripts.Render("~/bundles/tableexport")

    <script type="text/javascript">
        $(document).ready(
            function () {
                var table = $("#table-crud").DataTable();

                $("#table-crud").on("click", ".js-delete",
                    function () {
                        var deleteLink = $(this);
                        bootbox.confirm("Are you sure you want to delete this item?",
                            function(result) {
                                if (result) {
                                    $.ajax({
                                        url: "/finance/api/cardtypes/" + deleteLink.attr("data-cardtype-id"),
                                        method: "DELETE",
                                        success: function() {
                                            console.log("Successfully deleted Card Type: " + deleteLink.attr("data-cardtype-id"));
                                            table.row(deleteLink.parents("tr")).remove().draw();
                                        }
                                    });
                                }
                            }
                        );
                    }
                );

                $("#table-crud").tableExport({
                    formats: ["xlsx","xls", "csv", "txt"],
                    fileName: "Card Types",
                    position: "bottom"
                });

                
            }
        );
    </script>
}