Cubic ERP/Areas/Finance/Models/CashFlowSetup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cubic_ERP.Areas.Finance.Models
{
    public class CashFlowSetup
    {
        public int Id { get; set; }

        public int CashFlowHeadingId { get; set; }
        public int AccountMasterId { get; set; }

        public CashFlowHeading CashFlowHeading { get; set; }
        public AccountMaster AccountMaster { get; set; }

        public int? AuditUserId { get; set; }
        public DateTimeOffset? AuditTimeStamp { get; set; }

    }
}

Cubic ERP/Areas/Finance/Controllers/API/CashFlowSetupsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Cubic_ERP.Models;

namespace Cubic_ERP.Areas.Finance.Controllers.API
{
    public class CashFlowSetupsController : ApiController
    {
        private ApplicationDbContext _context;

        public CashFlowSetupsController()
        {
            _context=new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        //get list of cashflow setups
        [HttpGet]
        [Route("finance/api/cashflowsetups")]
        public IHttpActionResult Index()
        {
            return Ok(_context.CashFlowSetups.
                Include(c=>c.CashFlowHeading).
                Include(c=>c.AccountMaster).ToList());
        }

        //delete cashflow setup
        [HttpDelete]
        [Route("finance/api/cashflowsetups/{id}")]
        public IHttpActionResult DeleteCashFlowSetup(int id)
        {
            var cashfsInDb = _context.CashFlowSetups.Find(id);
            if (cashfsInDb==null)
            {
                return NotFound();
            }
            _context.CashFlowSetups.Remove(cashfsInDb);
            _context.SaveChanges();

            return Ok();
        }
    }
}

Cubic ERP/Areas/Finance/Controllers/Setups/CashFlowSetupController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cubic_ERP.Areas.Finance.Models;
using Cubic_ERP.Areas.Finance.ViewModels;
using Cubic_ERP.Models;

namespace Cubic_ERP.Areas.Finance.Controllers.Setups
{
    public class CashFlowSetupController : Controller
    {
        private ApplicationDbContext _context;

        public CashFlowSetupController()
        {
            _context=new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        //Get list of cash flow setups
        public ActionResult Index()
        {
            var cashfs = _context.CashFlowSetups.Include(c => c.CashFlowHeading)
                .Include(c => c.AccountMaster)
                .ToList();
            return View(cashfs);
        }

        //create new cash flow setup
        public ActionResult New()
        {
            var cashfs = new CashFlowSetup
            {
                Id = 0
            };
            var cashfsViewModel = new CashFlowSetupFormViewModel
            {
                ActionIndicator = 1,
                AccountMasters = _context.AccountMasters.ToList(),
                CashFlowHeadings = _context.CashFlowHeadings.ToList(),
                CashFlowSetup = cashfs
            };
            return View("CashFlowSetupForm",cashfsViewModel);
        }


        //edit existing cash flow setup
        public ActionResult Edit(int id)
        {
            var cashfsInDb = _context.CashFlowSetups.Find(id);
            var cashfsViewModel = new CashFlowSetupFormViewModel
            {
                ActionIndicator = 2,
                AccountMasters = _context.AccountMasters.ToList(),
                CashFlowHeadings = _context.CashFlowHeadings.ToList(),
                CashFlowSetup = cashfsInDb
            };
            return View("CashFlowSetupForm", cashfsViewModel);
        }

        //save cashflowsetup
        [HttpPost]
        public ActionResult Save(CashFlowSetupFormViewModel cashfsViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("CashFlowSetupForm", cashfsViewModel);
            }
            //else continue with new or edit
            if (cashfsViewModel.CashFlowSetup.Id==0) //means it's a new one
            {
                var cashfs = cashfsViewModel.CashFlowSetup;
                _context.CashFlowSetups.Add(cashfs);
                _context.SaveChanges();
            }
            else
            {
                var cashfsInDb = _context.CashFlowSetups.Find(cashfsViewModel.CashFlowSetup.Id);
                if (cashfsInDb==null)
                {
                    return HttpNotFound();
                }
                cashfsInDb.AccountMasterId = cashfsViewModel.CashFlowSetup.AccountMasterId;
                cashfsInDb.CashFlowHeadingId = cashfsViewModel.CashFlowSetup.CashFlowHeadingId;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Cubic ERP/Areas/Finance/Views/CashFlowSetup/CashFlowSetupForm.cshtml
@model Cubic_ERP.Areas.Finance.ViewModels.CashFlowSetupFormViewModel
@{
    ViewBag.Title = "Cash Flow Setups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h3 class="pull-left">Cash Flow Setups</h3>
    <a id="form-navigator" href="@Url.Action("Index", "CashFlowSetup")" class="btn btn-success btn-sm pull-right"><i class="glyphicon glyphicon-arrow-left"></i></a>
    <hr id="hr-separator" />
</div>

<div>
    <div class="col-md-5">
        @using (Html.BeginForm("Save", "CashFlowSetup", FormMethod.Post, new { @id = "form-submit" }))
        {

            <div class="row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.CashFlowSetup.CashFlowHeadingId)
                    @Html.DropDownListFor(m => m.CashFlowSetup.CashFlowHeadingId, new SelectList(Model.CashFlowHeadings, "Id", "CashFlowHeadingName"), "Select CashFlow Heading", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.CashFlowSetup.CashFlowHeadingId)
                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.CashFlowSetup.AccountMasterId)
                    @Html.DropDownListFor(m => m.CashFlowSetup.AccountMasterId, new SelectList(Model.AccountMasters, "Id", "Name"), "Select Account Master", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.CashFlowSetup.AccountMasterId)
                </div>
            </div>
        

            @Html.HiddenFor(m => m.CashFlowSetup.Id)

            if (Model.ActionIndicator == 1)
            {
                <button class="btn btn-primary" type="submit">Save</button>
            }
            else
            {
                <a href="#" class="btn btn-primary" id="js-edit">Save</a>
            }
            <a href="@Url.Action("Index","CashFlowSetup")" class="btn btn-default">Cancel</a>
        }
    </div>
</div>


@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(
            function() {
                $("#js-edit").on('click',
                    function () {

                        bootbox.confirm("Are you sure you want to Edit this item?",
                            function(result) {
                                if (result) {
                                    $("#form-submit").submit();
                                }
                            }
                        );
                    }
                );

            }
        );

    </script>
}

Cubic ERP/Areas/Finance/Views/CashFlowSetup/Index.cshtml
@model IEnumerable<Cubic_ERP.Areas.Finance.Models.CashFlowSetup>
@{
    ViewBag.Title = "Cash Flow Setups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@ViewBag.Title</h3>

<div>
    <a class="btn btn-default" href="@Url.Action("New","CashFlowSetup")">Add New</a>
</div>

<br />
<table id="table-crud" class="table table-responsive table-striped">
    <thead>
        <tr>
            <th>Actions</th>
            <th>#</th>
            <th>Cash Flow Heading</th>
            <th>Account Master</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cfSetup in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Edit","CashFlowSetup", new {id=cfSetup.Id})"><span class="glyphicon glyphicon-edit"></span></a>
                    <a href="#"><span class="glyphicon glyphicon-remove js-delete" data-cfsetup-id="@cfSetup.Id"></span></a>
                </td>
                <td>@cfSetup.Id</td>
                <td>@cfSetup.CashFlowHeading.CashFlowHeadingName</td>
                <td>@cfSetup.AccountMaster.Name</td>
                
            </tr>
        }

    </tbody>
</table>
@section scripts
{
    @Scripts.Render("~/bundles/tableexport")

    <script type="text/javascript">
        $(document).ready(
            function () {
                var table = $("#table-crud").DataTable();

                $("#table-crud").on("click", ".js-delete",
                    function () {
                        var deleteLink = $(this);
                        bootbox.confirm("Are you sure you want to delete this item?",
                            function(result) {
                                if (result) {
                                    $.ajax({
                                        url: "/finance/api/cashflowsetups/" + deleteLink.attr("data-cfsetup-id"),
                                        method: "DELETE",
                                        success: function() {
                                            console.log("Successfully deleted Cash Flow Setup: " + deleteLink.attr("data-cfsetup-id"));
                                            table.row(deleteLink.parents("tr")).remove().draw();
                                        }
                                    });
                                }
                            }
                        );
                    }
                );

                $("#table-crud").tableExport({
                    formats: ["xlsx","xls", "csv", "txt"],
                    fileName: "Cash Flow Setups",
                    position: "bottom"
                });

                
            }
        );
    </script>
}